name: POI修正提案（宿場・一里塚・本陣跡など）
description: 宿場の中心・一里塚・代表地点の位置ズレ、名称、説明など
title: "[POI] <街道名>：<地点名> 修正提案"
labels: ["poi", "needs-triage"]
body:
  - type: input
    id: kaido
    attributes:
      label: 街道名
      placeholder: 例）中山道
    validations:
      required: true

  - type: input
    id: poi_name
    attributes:
      label: 地点名（宿場名/一里塚/本陣跡など）
      placeholder: 例）奈良井宿 / ○○一里塚 / 本陣跡
    validations:
      required: true

  - type: dropdown
    id: poi_type
    attributes:
      label: 種別
      options:
        - 宿場
        - 一里塚
        - 本陣・脇本陣
        - 道標・分岐
        - 史跡・見どころ
        - その他
    validations:
      required: true

  - type: textarea
    id: change
    attributes:
      label: 修正内容（何をどう直したい？）
      placeholder: 例）現在の地点が駅寄りだが、宿場の中心は枡形跡周辺だと思う
    validations:
      required: true

  - type: input
    id: latlng
    attributes:
      label: 緯度経度（必須）
      placeholder: 35.xxxxxx, 137.xxxxxx
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: 根拠（URL・看板・写真など）
      placeholder: |
        例）
        - 現地案内板：写真あり
        - Wikipedia/自治体/観光協会：URL
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: 補足
    validations:
      required: false
