name: ルート修正提案（旧道・峠道・分岐など）
description: 街道ルート線のズレ・旧道／現代道の違いなど
title: "[Route] <街道名>：<区間> ルート修正提案"
labels: ["route", "needs-triage"]
body:
  - type: input
    id: kaido
    attributes:
      label: 街道名
      placeholder: 例）中山道 / 東海道 / 甲州街道 / 日光街道 / 奥州街道
    validations:
      required: true

  - type: input
    id: section
    attributes:
      label: 区間（○○宿〜○○宿）
      placeholder: 例）奈良井宿〜藪原宿
    validations:
      required: true

  - type: textarea
    id: diff
    attributes:
      label: 何が違う？（現状の問題点）
      description: 旧道/現代道/峠道/分岐/橋の位置/道筋など、具体的に
      placeholder: 例）現状は国道側に寄っているが、旧道は集落の裏を通る
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: 根拠（URL・現地看板・史料・写真など）
      description: URLが無い場合は「現地写真あり」などでOK（後で追加も可）
      placeholder: |
        例）
        - 自治体ページ： https://...
        - 現地看板：写真あり（後日添付）
        - 地形図： https://...
    validations:
      required: false

  - type: input
    id: latlng
    attributes:
      label: 緯度経度（必須）
      description: 例）35.123456, 137.123456
      placeholder: 35.xxxxxx, 137.xxxxxx
    validations:
      required: true

  - type: dropdown
    id: certainty
    attributes:
      label: 判断の確度
      options:
        - 高い（根拠あり）
        - 中（現地感覚・複数要素）
        - 低い（違和感のみ）
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: 補足
      placeholder: 例）旧道の写真／道標の位置／分岐の目印など
    validations:
      required: false
